DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "aclui.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "shrpubw.exe" or InitiatingProcessFileName endswith "oleview.exe")
| invoke FileProfile("SHA1", 1000)
