DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "activeds.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "applysettingstemplatecatalog.exe" or InitiatingProcessFileName endswith "agentservice.exe" or InitiatingProcessFileName endswith "dsadd.exe" or InitiatingProcessFileName endswith "dsget.exe" or InitiatingProcessFileName endswith "dsmod.exe" or InitiatingProcessFileName endswith "dsrm.exe" or InitiatingProcessFileName endswith "gpfixup.exe")
| invoke FileProfile("SHA1", 1000)
