DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "apphelp.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "compmgmtlauncher.exe" or InitiatingProcessFileName endswith "sdbinst.exe" or InitiatingProcessFileName endswith "explorer.exe")
| invoke FileProfile("SHA1", 1000)
