DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "basicnetutils.dll"
| where not(FolderPath contains "appdata\\local\\temp\\" and FolderPath contains "\\application2" or FolderPath contains "c:\\program files\\baidu\\baidupinyin\\") and (InitiatingProcessFileName endswith "xlgameupdate.exe")
| invoke FileProfile("SHA1", 1000)
