DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "clusapi.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "dfsrdiag.exe" or InitiatingProcessFileName endswith "msdtc.exe" or InitiatingProcessFileName endswith "tieringengineservice.exe" or InitiatingProcessFileName endswith "wbengine.exe")
| invoke FileProfile("SHA1", 1000)
