DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "cryptui.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "certutil.exe" or InitiatingProcessFileName endswith "efsui.exe" or InitiatingProcessFileName endswith "mstsc.exe" or InitiatingProcessFileName endswith "rekeywiz.exe")
| invoke FileProfile("SHA1", 1000)
