DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "d2d1.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "dataexchangehost.exe" or InitiatingProcessFileName endswith "dwm.exe" or InitiatingProcessFileName endswith "eoaexperiences.exe" or InitiatingProcessFileName endswith "gamepanel.exe" or InitiatingProcessFileName endswith "quickassist.exe" or InitiatingProcessFileName endswith "vsgraphicsdesktopengine.exe" or InitiatingProcessFileName endswith "vsgraphicsremoteengine.exe")
| invoke FileProfile("SHA1", 1000)
