DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "dbgmodel.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64" or FolderPath contains "c:\\program files\\windows kits\\10\\debuggers\\") and (InitiatingProcessFileName endswith "ntsd.exe")
| invoke FileProfile("SHA1", 1000)
