DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "dhcpcsvc.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "ipconfig.exe" or InitiatingProcessFileName endswith "netiougc.exe" or InitiatingProcessFileName endswith "netsh.exe")
| invoke FileProfile("SHA1", 1000)
