DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "dismapi.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "bootim.exe" or InitiatingProcessFileName endswith "deploymentcsphelper.exe" or InitiatingProcessFileName endswith "directxdatabaseupdater.exe" or InitiatingProcessFileName endswith "hvsievaluator.exe" or InitiatingProcessFileName endswith "resetengine.exe" or InitiatingProcessFileName endswith "systemreset.exe" or InitiatingProcessFileName endswith "systemsettingsadminflows.exe")
| invoke FileProfile("SHA1", 1000)
