DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "dmenrollengine.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "deviceenroller.exe" or InitiatingProcessFileName endswith "dmomacpmo.exe" or InitiatingProcessFileName endswith "mdmagent.exe" or InitiatingProcessFileName endswith "mdmappinstaller.exe" or InitiatingProcessFileName endswith "mdmdiagnosticstool.exe" or InitiatingProcessFileName endswith "omadmclient.exe" or InitiatingProcessFileName endswith "workfolders.exe")
| invoke FileProfile("SHA1", 1000)
