DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "dmenterprisediagnostics.dll"
| where not(FolderPath contains "c:\\windows\\system32") and (InitiatingProcessFileName endswith "deviceenroller.exe" or InitiatingProcessFileName endswith "omadmclient.exe")
| invoke FileProfile("SHA1", 1000)
