DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "dmiso8601utils.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "mdmdiagnosticstool.exe" or InitiatingProcessFileName endswith "mousocoreworker.exe" or InitiatingProcessFileName endswith "omadmclient.exe" or InitiatingProcessFileName endswith "usocoreworker.exe")
| invoke FileProfile("SHA1", 1000)
