DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "drvstore.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "infdefaultinstall.exe" or InitiatingProcessFileName endswith "securityhealthservice.exe")
| invoke FileProfile("SHA1", 1000)
