DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "dsparse.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "dcdiag.exe" or InitiatingProcessFileName endswith "dfsrdiag.exe" or InitiatingProcessFileName endswith "dmcertinst.exe" or InitiatingProcessFileName endswith "netdom.exe" or InitiatingProcessFileName endswith "rendom.exe")
| invoke FileProfile("SHA1", 1000)
