DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "dwrite.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "cttune.exe" or InitiatingProcessFileName endswith "dataexchangehost.exe" or InitiatingProcessFileName endswith "gamepanel.exe")
| invoke FileProfile("SHA1", 1000)
