DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "edgeiso.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "microsoftedgebchost.exe" or InitiatingProcessFileName endswith "microsoftedgecp.exe" or InitiatingProcessFileName endswith "microsoftedgedevtools.exe" or InitiatingProcessFileName endswith "microsoftedgesh.exe")
| invoke FileProfile("SHA1", 1000)
