DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "esent.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "dfsrdiag.exe" or InitiatingProcessFileName endswith "dsdbutil.exe" or InitiatingProcessFileName endswith "esentutl.exe" or InitiatingProcessFileName endswith "tieringengineservice.exe" or InitiatingProcessFileName endswith "ntdsutil.exe")
| invoke FileProfile("SHA1", 1000)
