DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "firewallapi.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "checknetisolation.exe" or InitiatingProcessFileName endswith "edpcleanup.exe" or InitiatingProcessFileName endswith "lpremove.exe" or InitiatingProcessFileName endswith "netsh.exe" or InitiatingProcessFileName endswith "securityhealthservice.exe" or InitiatingProcessFileName endswith "systemsettingsadminflows.exe")
| invoke FileProfile("SHA1", 1000)
