DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "framedynos.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "dfsrdiag.exe" or InitiatingProcessFileName endswith "driverquery.exe" or InitiatingProcessFileName endswith "getmac.exe" or InitiatingProcessFileName endswith "openfiles.exe" or InitiatingProcessFileName endswith "taskkill.exe")
| invoke FileProfile("SHA1", 1000)
