DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "fxsapi.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\system32\\driverstore\\filerepository\\prnms002.inf_" and FolderPath contains "\\amd64" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "fxsunatd.exe")
| invoke FileProfile("SHA1", 1000)
