DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "fxstiff.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\system32\\driverstore\\filerepository\\prnms002.inf_" and FolderPath contains "\\amd64") and (InitiatingProcessFileName endswith "fxssvc.exe")
| invoke FileProfile("SHA1", 1000)
