DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "hha.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64" or FolderPath contains "c:\\program files\\html help workshop") and (InitiatingProcessFileName endswith "hhc.exe")
| invoke FileProfile("SHA1", 1000)
