DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "httpapi.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "netsh.exe" or InitiatingProcessFileName endswith "wifitask.exe" or InitiatingProcessFileName endswith "wsmanhttpconfig.exe")
| invoke FileProfile("SHA1", 1000)
