DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "ifsutil.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "convert.exe" or InitiatingProcessFileName endswith "fsavailux.exe" or InitiatingProcessFileName endswith "label.exe" or InitiatingProcessFileName endswith "recover.exe" or InitiatingProcessFileName endswith "xcopy.exe")
| invoke FileProfile("SHA1", 1000)
