DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "lmiguardiandll.dll"
| where not(FolderPath contains "c:\\program files\\logmein" or FolderPath contains "c:\\program files\\logmein\\x86" or FolderPath contains "c:\\program files\\logmein\\x64") and (InitiatingProcessFileName endswith "lmiguardiansvc.exe")
| invoke FileProfile("SHA1", 1000)
