DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "mintdh.dll"
| where not(FolderPath contains "c:\\windows\\system32") and (InitiatingProcessFileName endswith "applytrustoffline.exe" or InitiatingProcessFileName endswith "netsh.exe" or InitiatingProcessFileName endswith "pktmon.exe" or InitiatingProcessFileName endswith "plasrv.exe")
| invoke FileProfile("SHA1", 1000)
