DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "mscoree.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "aitstatic.exe" or InitiatingProcessFileName endswith "presentationhost.exe" or InitiatingProcessFileName endswith "applaunch.exe")
| invoke FileProfile("SHA1", 1000)
