DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "msdrm.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "gamepanel.exe" or InitiatingProcessFileName endswith "psr.exe" or InitiatingProcessFileName endswith "rmactivate.exe" or InitiatingProcessFileName endswith "rmactivate_isv.exe" or InitiatingProcessFileName endswith "snippingtool.exe")
| invoke FileProfile("SHA1", 1000)
