DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "msftedit.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "charmap.exe" or InitiatingProcessFileName endswith "mspaint.exe" or InitiatingProcessFileName endswith "searchindexer.exe" or InitiatingProcessFileName endswith "searchprotocolhost.exe")
| invoke FileProfile("SHA1", 1000)
