DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "msi.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "dxpserver.exe" or InitiatingProcessFileName endswith "fondue.exe" or InitiatingProcessFileName endswith "mdmappinstaller.exe" or InitiatingProcessFileName endswith "msiexec.exe" or InitiatingProcessFileName endswith "optionalfeatures.exe" or InitiatingProcessFileName endswith "packageinspector.exe")
| invoke FileProfile("SHA1", 1000)
