DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "ntmarta.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "cacls.exe" or InitiatingProcessFileName endswith "chrome.exe" or InitiatingProcessFileName endswith "msedge.exe" or InitiatingProcessFileName endswith "msedgewebview2.exe")
| invoke FileProfile("SHA1", 1000)
