DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "pdh.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "plasrv.exe" or InitiatingProcessFileName endswith "relog.exe" or InitiatingProcessFileName endswith "taskmgr.exe" or InitiatingProcessFileName endswith "tracerpt.exe" or InitiatingProcessFileName endswith "typeperf.exe" or InitiatingProcessFileName endswith "logman.exe")
| invoke FileProfile("SHA1", 1000)
