DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "powrprof.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "fsquirt.exe" or InitiatingProcessFileName endswith "msinfo32.exe" or InitiatingProcessFileName endswith "printfilterpipelinesvc.exe" or InitiatingProcessFileName endswith "sfc.exe")
| invoke FileProfile("SHA1", 1000)
