DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "python39.dll"
| where not(FolderPath contains "c:\\program files\\python39" or FolderPath contains "appdata\\local\\temp\\" or FolderPath contains "c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\vc\\securityissueanalysis\\python" or FolderPath contains "\\anaconda3") and (InitiatingProcessFileName endswith "python39.exe")
| invoke FileProfile("SHA1", 1000)
