DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "resetengine.dll"
| where not(FolderPath contains "c:\\windows\\system32") and (InitiatingProcessFileName endswith "resetengine.exe" or InitiatingProcessFileName endswith "systemreset.exe")
| invoke FileProfile("SHA1", 1000)
