DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "rtutils.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "dialer.exe" or InitiatingProcessFileName endswith "nethost.exe" or InitiatingProcessFileName endswith "rasautou.exe" or InitiatingProcessFileName endswith "rasdial.exe" or InitiatingProcessFileName endswith "rasphone.exe")
| invoke FileProfile("SHA1", 1000)
