DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "samlib.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "dpapimig.exe" or InitiatingProcessFileName endswith "dsmgmt.exe" or InitiatingProcessFileName endswith "easinvoker.exe" or InitiatingProcessFileName endswith "netplwiz.exe" or InitiatingProcessFileName endswith "ntdsutil.exe")
| invoke FileProfile("SHA1", 1000)
