DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "spp.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "rstrui.exe" or InitiatingProcessFileName endswith "sdclt.exe" or InitiatingProcessFileName endswith "srtasks.exe" or InitiatingProcessFileName endswith "wbengine.exe")
| invoke FileProfile("SHA1", 1000)
