DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "srmtrace.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "dirquota.exe" or InitiatingProcessFileName endswith "filescrn.exe" or InitiatingProcessFileName endswith "storrept.exe")
| invoke FileProfile("SHA1", 1000)
