DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "staterepository.core.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "applytrustoffline.exe" or InitiatingProcessFileName endswith "lpremove.exe" or InitiatingProcessFileName endswith "systemsettingsadminflows.exe")
| invoke FileProfile("SHA1", 1000)
