DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "tapi32.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "dialer.exe" or InitiatingProcessFileName endswith "fxssvc.exe" or InitiatingProcessFileName endswith "tcmsetup.exe")
| invoke FileProfile("SHA1", 1000)
