DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "tbs.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "bootim.exe" or InitiatingProcessFileName endswith "mdmdiagnosticstool.exe" or InitiatingProcessFileName endswith "resetengine.exe" or InitiatingProcessFileName endswith "sgrmbroker.exe" or InitiatingProcessFileName endswith "systemreset.exe" or InitiatingProcessFileName endswith "tpmtool.exe")
| invoke FileProfile("SHA1", 1000)
