DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "updatepolicy.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "mousocoreworker.exe" or InitiatingProcessFileName endswith "musnotification.exe" or InitiatingProcessFileName endswith "musnotificationux.exe" or InitiatingProcessFileName endswith "usoclient.exe" or InitiatingProcessFileName endswith "usocoreworker.exe")
| invoke FileProfile("SHA1", 1000)
