DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "upshared.dll"
| where not(FolderPath contains "c:\\windows\\system32") and (InitiatingProcessFileName endswith "musnotification.exe" or InitiatingProcessFileName endswith "musnotificationux.exe" or InitiatingProcessFileName endswith "musnotifyicon.exe")
| invoke FileProfile("SHA1", 1000)
