DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "urlmon.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "bytecodegenerator.exe" or InitiatingProcessFileName endswith "ie4uinit.exe" or InitiatingProcessFileName endswith "ldifde.exe" or InitiatingProcessFileName endswith "presentationhost.exe" or InitiatingProcessFileName endswith "write.exe")
| invoke FileProfile("SHA1", 1000)
