DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "utildll.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "change.exe" or InitiatingProcessFileName endswith "chglogon.exe" or InitiatingProcessFileName endswith "chgport.exe" or InitiatingProcessFileName endswith "query.exe" or InitiatingProcessFileName endswith "quser.exe" or InitiatingProcessFileName endswith "qprocess.exe" or InitiatingProcessFileName endswith "qwinsta.exe" or InitiatingProcessFileName endswith "reset.exe" or InitiatingProcessFileName endswith "rwinsta.exe" or InitiatingProcessFileName endswith "tscon.exe" or InitiatingProcessFileName endswith "tskill.exe")
| invoke FileProfile("SHA1", 1000)
