DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "vivaldi_elf.dll"
| where not(FolderPath contains "appdata\\local\\vivaldi\\application" or FolderPath contains "appdata\\local\\vivaldi\\application\\") and (InitiatingProcessFileName endswith "vivaldi.exe")
| invoke FileProfile("SHA1", 1000)
