DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "wdi.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "cofire.exe" or InitiatingProcessFileName endswith "msra.exe" or InitiatingProcessFileName endswith "netsh.exe" or InitiatingProcessFileName endswith "dpiscaling.exe" or InitiatingProcessFileName endswith "slui.exe")
| invoke FileProfile("SHA1", 1000)
