DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "webservices.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "clipup.exe" or InitiatingProcessFileName endswith "sppsvc.exe" or InitiatingProcessFileName endswith "vsgraphicsdesktopengine.exe" or InitiatingProcessFileName endswith "vsgraphicsremoteengine.exe" or InitiatingProcessFileName endswith "wifitask.exe" or InitiatingProcessFileName endswith "wksprt.exe")
| invoke FileProfile("SHA1", 1000)
