DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "wimgapi.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64" or FolderPath contains "c:\\program files\\windows kits\\10\\assessment and deployment kit\\deployment tools\\arm64\\dism") and (InitiatingProcessFileName endswith "recoverydrive.exe" or InitiatingProcessFileName endswith "resetengine.exe" or InitiatingProcessFileName endswith "systemreset.exe" or InitiatingProcessFileName endswith "dism.exe")
| invoke FileProfile("SHA1", 1000)
