DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "windowsperformancerecordercontrol.dll"
| where not(FolderPath contains "c:\\program files\\windows kits\\10\\windows performance toolkit" or FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "wpr.exe")
| invoke FileProfile("SHA1", 1000)
