DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "windowsperformancerecorderui.dll"
| where not(FolderPath contains "c:\\program files\\windows kits\\10\\windows performance toolkit") and (InitiatingProcessFileName endswith "wprui.exe")
| invoke FileProfile("SHA1", 1000)
