DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "windows.storage.search.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "certreq.exe" or InitiatingProcessFileName endswith "control.exe" or InitiatingProcessFileName endswith "explorer.exe" or InitiatingProcessFileName endswith "notepad.exe")
| invoke FileProfile("SHA1", 1000)
