DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "winscard.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "immersivetpmvscmgrsvr.exe" or InitiatingProcessFileName endswith "rmttpmvscmgrsvr.exe" or InitiatingProcessFileName endswith "tpmvscmgrsvr.exe")
| invoke FileProfile("SHA1", 1000)
