DeviceImageLoadEvents
| extend FileName = tolower(FileName), FolderPath = tolower(FolderPath), InitiatingProcessFileName = tolower(InitiatingProcessFileName)
| where Filename == "wofutil.dll"
| where not(FolderPath contains "c:\\windows\\system32" or FolderPath contains "c:\\windows\\syswow64") and (InitiatingProcessFileName endswith "recoverydrive.exe" or InitiatingProcessFileName endswith "resetengine.exe" or InitiatingProcessFileName endswith "systemreset.exe")
| invoke FileProfile("SHA1", 1000)
